# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rack'
gem 'connection_pool'
gem 'pg'

group :falcon, optional: true do
  gem 'falcon'
end

group :iodine, optional: true do
  gem 'rage-rb'
end

group :puma, optional: true do
  gem 'puma', ENV['PUMA_VERSION']
end
