services:
  puma:
    cpus: "2"
    environment:
      WORKERS: "2"
      SERVER: "puma"
      PORT: 3000
    build:
      context: ./ruby
      dockerfile: puma.Dockerfile
    volumes:
      - ./ruby/puma.rb:/puma.rb
      - ./ruby/config.ru:/config.ru
    network_mode: host

  falcon:
    cpus: "2"
    environment:
      WORKERS: "2"
      SERVER: "falcon"
      PORT: 3001
    build:
      context: ./ruby
      dockerfile: falcon.Dockerfile
    volumes:
      - ./ruby/falcon.rb:/falcon.rb
      - ./ruby/config.ru:/config.ru
    network_mode: host

  crystal:
    cpus: "2"
    environment:
      PORT: 3002
    build: ./crystal
    volumes:
      - ./crystal/run.sh:/run.sh
    network_mode: host
    depends_on:
      postgres:
        condition: service_healthy

  go:
    cpus: "2"
    environment:
      PORT: 3003
    build: ./go
    network_mode: host

  nodejs:
    cpus: "2"
    environment:
      PORT: 3004
    build: ./nodejs
    network_mode: host
    volumes:
      - ./nodejs/server.js:/server.js
      - ./nodejs/app.js:/app.js

  python:
    cpus: "2"
    environment:
      PORT: 3005
    build: ./python
    network_mode: host
    volumes:
      - ./python/main.py:/main.py
      - ./python/uvicorn_conf.py:/uvicorn_conf.py
      - ./python/uvicorn_worker.py:/uvicorn_worker.py

  kamal-proxy:
    cpus: "2"
    environment:
      HTTP_PORT: 8080
      HTTPS_PORT: 8081
    build: kamal-proxy
    restart: unless-stopped
    network_mode: host
    logging:
      driver: none

  nginx:
    cpus: "2"
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - puma
      - falcon
      - go
    network_mode: host

  postgres:
    image: postgres:17
    command: -c 'max_connections=200'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db1
    network_mode: host
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "db1"]